### ISSUE TITLE
How to generate signed certificates?

### ISSUE THREAD

**Issue by sivai2i** [guix77/react-blockcerts#5]
I am curious to know how to generate signed certificates. I want to use open badges and is there any way  to use ?

**Comment by guix77** [comment]
It's not the project where to ask this, but anyways...

First you have to generate unsigned certificates, for instance with Cert-tools (https://github.com/blockchain-certificates/cert-tools), by hand using an unsigned certificate template following/extending the BlockCerts specs, or coding your own tool (I don't think there are any opensource projects).

Then you have to sign them for instance with Cert-issuer (https://github.com/blockchain-certificates/cert-issuer) and again I don't think there are other tools available.

**Comment by sivai2i** [comment]
Thanks for your quick response
